/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/product` | `/product`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/text` | `/text`; params?: Router.UnknownInputParams; } | { pathname: `/business/add-business`; params?: Router.UnknownInputParams; } | { pathname: `/business/my-business`; params?: Router.UnknownInputParams; } | { pathname: `/businessdetail/[businessid]`, params: Router.UnknownInputParams & { businessid: string | number; } } | { pathname: `/businesslist/[category]`, params: Router.UnknownInputParams & { category: string | number; } } | { pathname: `/productdetail/[productid]`, params: Router.UnknownInputParams & { productid: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/product` | `/product`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/text` | `/text`; params?: Router.UnknownOutputParams; } | { pathname: `/business/add-business`; params?: Router.UnknownOutputParams; } | { pathname: `/business/my-business`; params?: Router.UnknownOutputParams; } | { pathname: `/businessdetail/[businessid]`, params: Router.UnknownOutputParams & { businessid: string; } } | { pathname: `/businesslist/[category]`, params: Router.UnknownOutputParams & { category: string; } } | { pathname: `/productdetail/[productid]`, params: Router.UnknownOutputParams & { productid: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cart${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/product${`?${string}` | `#${string}` | ''}` | `/product${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/text${`?${string}` | `#${string}` | ''}` | `/text${`?${string}` | `#${string}` | ''}` | `/business/add-business${`?${string}` | `#${string}` | ''}` | `/business/my-business${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/product` | `/product`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/text` | `/text`; params?: Router.UnknownInputParams; } | { pathname: `/business/add-business`; params?: Router.UnknownInputParams; } | { pathname: `/business/my-business`; params?: Router.UnknownInputParams; } | `/businessdetail/${Router.SingleRoutePart<T>}` | `/businesslist/${Router.SingleRoutePart<T>}` | `/productdetail/${Router.SingleRoutePart<T>}` | { pathname: `/businessdetail/[businessid]`, params: Router.UnknownInputParams & { businessid: string | number; } } | { pathname: `/businesslist/[category]`, params: Router.UnknownInputParams & { category: string | number; } } | { pathname: `/productdetail/[productid]`, params: Router.UnknownInputParams & { productid: string | number; } };
    }
  }
}
